## => Language and Timezone
lang: en # the language of your site, default as "en"

## => Author and Social
author:
  name      : naheenosaur
  email     : naheenosaur@gmail.com
  github    : https://github.com/naheenosaur

## => GitHub Repository (if the site is hosted by GitHub)
##############################
#repository: naheenosaur/heestory
#repository_tree: master

## TOC
toc:
  selectors: # "h1,h2,h3" (default)

## => Paginate
paginate: 8
paginate_path: /page:num # don't change this unless for special need

## => Comments
##############################
#comments:
#  provider: disqus
#  disqus:
#   shortname: # the Disqus shortname for the site

## => Pageview
#pageview:
#  provider: false # false (default), "leancloud", "custom"

## => Search
search:
  provider: default # "default" (default), false, "google", "custom"
##   Google Custom Search Engine
#    google:
#    custom_search_engine_id: # Google Custom Search Engine ID

## => Analytics
##############################
#analytics:
#  provider: false # false (default), "google", "custom"
  ## Google Analytics
  # google:
          #    tracking_id : # Google Analytics id for the site
          #    anonymize_ip: false # Anonymize IP tracking for Analytics

## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # code theme
#url     : https://naheenosaur.github.io/heestory  # the base hostname & protocol for your site e.g. https://www.someone.com
#baseurl : /heestory  # does not include hostname
url     : https://naheenosaur.github.io  # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl :   # does not include hostname
title   : divide and conquer
#description: > # this means to ignore newlines until "Language & timezone"
#  naheenosaur.kr

## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : /:title

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    day: /:year/:month/:day/
    tag: /tag/:name/
    category: /category/:name/

## => Paths
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true

## => Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
