## => Language and Timezone
lang: en # the language of your site, default as "en"

## => Author and Social
author:
  name      : naheenosaur
  email     : naheenosaur@gmail.com
  github    : naheenosaur

## => GitHub Repository (if the site is hosted by GitHub)
#repository: naheenosaur.github.io
#repository_tree: master

## TOC
toc:
  selectors: # "h1,h2,h3" (default)

## => Paginate
paginate: 8
paginate_path: /page:num # don't change this unless for special need

## => Comments
#comments:
#  provider: disqus
#  disqus:
#   shortname: # the Disqus shortname for the site

## => Pageview
#pageview:
#  provider: false # false (default), "leancloud", "custom"

## => Search
search:
  provider: default # "default" (default), false, "google", "custom"
##   Google Custom Search Engine
#    google:
#    custom_search_engine_id: # Google Custom Search Engine ID

## => Analytics
#analytics:
#  provider: false # false (default), "google", "custom"
  ## Google Analytics
  # google:
          #    tracking_id : # Google Analytics id for the site
          #    anonymize_ip: false # Anonymize IP tracking for Analytics

## => Site Settings
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # code theme
url     : https://naheenosaur.github.io  # the base hostname & protocol for your site e.g. https://www.someone.com
#baseurl :   # does not include hostname
title   : divide and conquer
#description: > # this means to ignore newlines until "Language & timezone"
#  naheenosaur.kr

## => Build
markdown    : kramdown
highlighter : rouge
permalink   : /:title

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    day: /:year/:month/:day/
    tag: /tag/:name/
    category: /category/:name/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package-lock.json
  - package.json

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: false
      show_subscribe: true
      pageview: true
  - scope:  ## g11n
      path: "_g11n"
    values:
      layout: document
      nav_key: g11n
      sidebar:
        nav: g11n
      license: true
      aside:
        toc: true
      show_edit_on_github: false
      show_date: false
  - scope:  ## review
      path: "_review"
    values:
      layout: document
      nav_key: review
      sidebar:
        nav: review
      license: true
      aside:
        toc: true
      show_edit_on_github: false
      show_date: false

collections:
  g11n:
    output: true
  review:
    output: true

## => Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
